apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames: ["{{ .Release.Name }}-configmap"]
  verbs: ["get", "watch", "list"]
